package org.satochip.satodime.util

enum class SatodimeScreen {
    FirstWelcome,
    SecondWelcome,
    ThirdWelcome,
    SelectBlockchain,
    CreateVault,
    CongratsVaultCreated,
    Vaults,
    AddFunds,
    UnsealWarning,
    UnsealCongrats,
    ShowPrivateKey,
    ShowPrivateKeyData,
    ExpertMode,
    ResetWarningView,
    ResetCongratsView,
    MenuView,
    CardInfoView,
    TransferOwnershipView,
    SettingsView,
    ShowLogsView,
    AuthenticCardView,
    FakeCardView,
}